---
booktitle: Proceedings of the First Workshop on Applications of Pattern Analysis
publisher: JMLR Workshop and Conference Proceedings
logoright: basic_files/logo.png
volume: 11
month: 0
year: '2010'
start: 2010-09-01
end: 2010-09-03
published: 2010-09-30
shortname: Workshop on Applications of Pattern Analysis
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: DieteWAPA2010
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Tom
  family: Diethe
- given: Nello
  family: Cristianini
- given: John
  family: Shawe-Taylor
description: |
  Proceedings of the First Workshop on Applications of Pattern Analysis
    Held in Cumberland Lodge, Windsor, UK on 01-03 September 2010

  Published as Volume 11 by the Proceedings of Machine Learning Research on 30 September 2010.

  Volume Edited by:
    Tom Diethe
    Nello Cristianini
    John Shawe-Taylor

  Series Editors:
    Neil D. Lawrence
date_str: 01--03 Sep
url: http://proceedings.mlr.press
baseurl: "/v11"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v11
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Proceedings of the First Workshop on Applications of Pattern Analysis
  url: 
  location: Cumberland Lodge, Windsor, UK
  dates:
  - 2010-09-01
  - 2010-09-02
  - 2010-09-03
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v11.bib
